config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects

  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :tags, except: :show

  resources :users, only: :create
  get 'signup', to: 'users#new'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/shared/_errors.html.haml
- if model.errors.any?
  .text-danger
    %h3 #{model.errors.size} #{'error'.pluralize(model.errors.size)} prohibited this #{model.class.name.downcase} from being saved:
    %ul
      - model.errors.full_messages.each do |error_msg|
        %li= error_msg

app/views/shared/_flash_msg.html.haml
- if flash[:success]
  %p.text-success= flash[:success]
- elsif flash[:error]
  %p.text-danger= flash[:error]

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand.navbar-dark.justify-content-between.p-0
  .container.justify-content-start
    %h1.navbar-brand Ticketing
    %ul.navbar-nav.flex-row
      %li.nav-item.active= link_to 'Projects', projects_path, class: 'nav-link'
      %li.nav-item= link_to 'Tickets', tickets_path, class: 'nav-link'
      %li.nav-item= link_to 'Tags', tags_path, class: 'nav-link'
  .container.justify-content-end
    - if logged_in?
      Signed in as #{current_user.name}
      %span.p-1
      = link_to 'Logout', logout_path, method: :delete
    - else
      = link_to 'Login', login_path
      %span.p-1 or
      = link_to 'Signup', signup_path