config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects

  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :tags, except: :show

  resources :users, only: :create
  get 'signup', to: 'users#new'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  STATUSES = { 'New' => 'new', 'Blocked' => 'blocked', 'In Progress' => 'in_progress', 'Fixed' => 'fixed' }.freeze

  belongs_to :project
  has_many :tag_tickets, dependent: :destroy
  has_many :tags, through: :tag_tickets
  belongs_to :creator,  class_name: 'User', foreign_key: 'user_id'
  belongs_to :assignee, class_name: 'User', foreign_key: 'assignee_id', optional: true
  has_many :comments, dependent: :destroy

  validates_presence_of :name

  def fixed?
    status == 'fixed'
  end

  def comments?
    !comments.empty?
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :find_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.where params.permit(:project, :status).reject { |k, v| v.blank? }
    tag = params.permit(:tag)[:tag]
    @tickets = @tickets.select { |ticket| ticket.tags.map(&:id).include? tag.to_i } unless tag.blank?
  end

  def show
    @comment = Comment.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new get_params.merge(creator: current_user)
    if @ticket.save
      flash[:success] = 'Ticket was successfully created.'
      redirect_to ticket_path(@ticket)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ticket.update get_params
      flash[:success] = 'Ticket was successfully updated.'
      redirect_to ticket_path(@ticket)
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    flash[:success] = 'Ticket was successfully deleted.'
    redirect_to tickets_path
  end

  private
    def find_ticket
      @ticket = Ticket.find params[:id]
    end

    def get_params
      params.require(:ticket).permit(:project_id, :name, :body, :status, :assignee_id, tag_ids: [])
    end
end

app/views/tickets/_form.html.haml
= render 'shared/errors', model: @ticket
= form_with model: @ticket, local: true do |f|
  .form-group
    = f.label :project
    %br
    = f.collection_select :project_id, Project.all, :id, :name
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control bg-dark'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control bg-dark'
  .form-group
    = f.label :status
    %br
    = f.select :status, Ticket::STATUSES
  .form-group
    = f.label :assignee_id, 'Assigned To'
    %br
    = f.collection_select :assignee_id, User.all, :id, :name, include_blank: 'No one'
  .form-group
    = f.label :tag_ids
    %br
    = f.collection_select :tag_ids, Tag.all, :id, :name, {}, multiple: true
  .form-group.actions
    = f.submit nil, class: 'btn btn-primary'

app/views/tickets/_table.html.haml
%table.table.table-dark
  %thead
    %tr
      %th Name
      %th Assignee
      %th Status
      %th Tags
      %th
  %tbody
    - tickets.each do |ticket|
      %tr
        %td= link_to ticket.name, ticket_path(ticket)
        %td= ticket.assignee&.name
        %td= format_ticket_status(ticket.status)
        %td= format_tags(ticket.tags)
        %td
          = link_to 'Edit', edit_ticket_path(ticket)
          = link_to 'Delete', ticket_path(ticket), method: :delete, 'data-confirm': 'Are you sure?'

app/views/tickets/edit.html.haml
%h2 Editing Ticket
= render 'form'

app/views/tickets/index.html.haml
%h2 Tickets
= form_with local: true, method: :get, skip_enforcing_utf8: true do |f|
  .form-group.d-inline
    = f.label :project, 'Show tickets from'
    = f.collection_select :project, Project.all, :id, :name, selected: params[:project], include_blank: 'All Projects'
  .form-group.d-inline
    = f.label :status, 'with status'
    = f.select :status, Ticket::STATUSES, selected: params[:status], include_blank: 'Any Status'
  .form-group.d-inline
    = f.label :tag, 'tagged'
    = f.collection_select :tag, Tag.all, :id, :name, selected: params[:tag], include_blank: '-'
  .form-group.actions.d-inline
    = f.submit 'Update', name: nil, class: 'btn btn-primary'
    = link_to 'Clear Filters', tickets_path
%br
- if @tickets.empty?
  %p
    There are no tickets matching the selected filters.
    = link_to 'Clear filters and show all tickets', tickets_path
- else
  = render 'table', tickets: @tickets
.mt-4= link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.haml
%h2 New Ticket
= render 'form'

app/views/tickets/show.html.haml
%h2= @ticket.name
%p= @ticket.body
%p
  %span.font-weight-bold Tags:
  = format_tags(@ticket.tags)
%p
  = link_to 'Edit', edit_ticket_path(@ticket)
  = link_to 'Delete', ticket_path(@ticket), method: :delete, 'data-confirm': 'Are you sure?'
%table.table.table-dark.border-bottom
  %thead
    %tr
      %th Status
      %th Creator
      %th Assignee
  %tbody
    %tr
      %td= format_ticket_status(@ticket.status)
      %td= @ticket.creator.name
      %td= @ticket.assignee&.name
%h3 Comments
- if @ticket.comments?
  - @ticket.comments.each do |comment|
    .card.bg-dark
      .card-body
        %p= comment.body
        %p.small posted by #{comment.creator.name} #{format_timestamps comment}
        = link_to 'Edit', edit_ticket_comment_path(@ticket, comment)
        = link_to 'Delete', ticket_comment_path(@ticket, comment), method: :delete, 'data-confirm': 'Are you sure?'
- else
  %p There are no comments.
= render 'comments/form'