config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects

  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :tags, except: :show

  resources :users, only: :create
  get 'signup', to: 'users#new'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tickets, dependent: :destroy

  validates_presence_of :name

  def total_tickets
    tickets.size
  end

  def fixed_tickets
    tickets.count &:fixed?
  end

  def open_tickets
    total_tickets - fixed_tickets
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :find_project, only:   [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new get_params
    if @project.save
      flash[:success] = 'Project was successfully created.'
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update get_params
      flash[:success] = 'Project was successfully updated.'
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:success] = 'Project was successfully deleted.'
    redirect_to projects_path
  end

  private
    def find_project
      @project = Project.find params[:id]
    end

    def get_params
      params.require(:project).permit(:name, :description)
    end
end

app/views/projects/_form.html.haml
= render 'shared/errors', model: @project
= form_with model: @project, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control bg-dark'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control bg-dark'
  .form-group.actions
    = f.submit nil, class: 'btn btn-primary'

app/views/projects/edit.html.haml
%h2 Editing Project
= render 'form'
%p
  = link_to 'Show', project_path(@project)
  = link_to 'Back', projects_path

app/views/projects/index.html.haml
%h2 Projects
- if @projects.empty?
  %p There are no projects.
- else
  %table.table.table-dark
    %thead
      %tr.border-bottom
        %th Name
        %th.text-center Open Tickets
        %th.text-center Total Tickets
    %tbody
      - @projects.each do |project|
        %tr
          %td
            = link_to project.name, project_path(project)
            %p= project.description
          %td.text-center= project.open_tickets
          %td.text-center= project.total_tickets
.mt-4= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h2 New Project
= render 'form'
%p= link_to 'Back', projects_path

app/views/projects/show.html.haml
%h2= @project.name
%p= @project.description
%p
  = link_to 'Edit', edit_project_path(@project)
  = link_to 'Delete', project_path(@project), method: :delete, 'data-confirm': 'Are you sure?'
%h3 Tickets
= render 'tickets/table', tickets: @project.tickets