config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects

  resources :tickets do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  resources :tags, except: :show

  resources :users, only: :create
  get 'signup', to: 'users#new'

  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_tickets, dependent: :destroy
  has_many :tickets, through: :tag_tickets

  validates_presence_of :name
  validates :name, format: { with: /\A[^,]*\z/, message: "can't contain commas" }

  default_scope { order Arel.sql('lower(name)') }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_user, except: [:index, :show]
  before_action :find_tag, only: [:edit, :update, :destroy]

  def index 
    # SELECT DISTINCT tags.*, COUNT(tag_tickets.tag_id) AS tickets_count FROM tags
    # LEFT OUTER JOIN tag_tickets ON tags.id = tag_tickets.tag_id
    # GROUP BY tags.id;
    @tags = Tag.left_outer_joins(:tag_tickets).distinct.select('tags.*, COUNT(tag_tickets.tag_id) AS tickets_count').group('tags.id')
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new get_params
    if @tag.save
      flash[:success] = 'Tag was successfully created.'
      redirect_to tags_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tag.update get_params
      flash[:success] = 'Tag was successfully updated.'
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    flash[:success] = 'Tag was successfully deleted.'
    redirect_to tags_path
  end

  private
    def find_tag
      @tag = Tag.find params[:id]
    end

    def get_params
      params.require(:tag).permit(:name)
    end
end

app/views/tags/_form.html.haml
= render 'shared/errors', model: @tag
= form_with model: @tag, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control bg-dark'
  .form-group.actions
    = f.submit nil, class: 'btn btn-primary'
= link_to 'Back', tags_path

app/views/tags/edit.html.haml
%h2 Editing Tag
= render 'form'

app/views/tags/index.html.haml
%h2 Tags
- if @tags.empty?
  %p There are no tags.
- else
  %table.table.table-dark
    %thead
      %tr.border-bottom
        %th Name
        %th.text-center Tickets
        %th
    %tbody
      - @tags.each do |tag|
        %tr
          %td= tag.name
          %td.text-center= link_to tag.tickets_count, tickets_path(tag: tag.id)
          %td
            = link_to 'Edit', edit_tag_path(tag)
            = link_to 'Delete', tag_path(tag), method: :delete, 'data-confirm': 'Are you sure?'
.mt-4= link_to 'New Tag', new_tag_path

app/views/tags/new.html.haml
%h2 New Tag
= render 'form'